import { PolicyData } from '../types';

export const SAMPLE_POLICIES: PolicyData[] = [
  {
    id: 'hdfc-ergo-optima-secure',
    insurerName: 'HDFC ERGO General Insurance',
    policyName: 'Optima Secure',
    policyNumber: 'HDFC-OS-2026-99812',
    sumInsured: '₹ 10,00,000',
    policyPeriod: '01 Jan 2026 – 31 Dec 2026',
    familyMembers: '4 (Self + Spouse + 2 Children)',
    userName: 'Sai',
    insurerHelpline: '1800 2666 400',
    tpaName: 'HDFC ERGO In-House Health TPA',
    tpaHelpline: '022 6234 6234',
    cashlessNumber: 'AUTH-HDFC-882194',
    fields: [
      {
        field: 'room_rent_cap',
        title: 'Room Rent Limit',
        category: 'caps',
        value: 'No Cap (Any Single Private AC Room)',
        status: 'covered',
        quote: 'The insured person is entitled to admission in Any Room Category except Suite or above, with no room rent capping.',
        page: 12,
        clause: '4.2.1',
        explanation: 'Your policy covers any single private AC room with zero sub-limit. No proportionate deduction applies for single room categories.',
        plainMeaning: 'You can choose any standard single private room without worrying about proportionate cuts on your doctor fees or surgery bills.',
        iconName: 'Bed',
        relatedFields: [
          { title: 'ICU charges', clause: '4.3.1', page: 13 },
          { title: 'Nursing charges', clause: '4.4.2', page: 14 }
        ]
      },
      {
        field: 'icu_cap',
        title: 'ICU Charges Limit',
        category: 'caps',
        value: 'No Sub-limit (Covered up to Sum Insured)',
        status: 'covered',
        quote: 'Intensive Care Unit (ICU) / Intensive Cardiac Care Unit (ICCU) charges are covered up to the Sum Insured.',
        page: 13,
        clause: '4.3.1',
        explanation: 'All ICU and ICCU charges including monitoring and specialist rounds are payable up to your ₹10 Lakh sum insured.',
        plainMeaning: 'Full coverage for emergency ICU treatments without daily limits.',
        iconName: 'Activity'
      },
      {
        field: 'copay_percentage',
        title: 'Co-payment Requirement',
        category: 'caps',
        value: '0% (Zero Co-payment)',
        status: 'covered',
        quote: 'No mandatory co-payment is applicable across all age groups at network and non-network hospitals.',
        page: 15,
        clause: '5.1',
        explanation: 'You do not have to pay a fixed percentage of your hospital bill from your own pocket.',
        plainMeaning: 'The insurer pays 100% of the approved bill with zero deduction for co-pay.',
        iconName: 'Percent'
      },
      {
        field: 'initial_waiting_period',
        title: 'Initial Waiting Period',
        category: 'waiting',
        value: '30 Days',
        status: 'covered',
        quote: 'A waiting period of 30 days from the inception date applies for all illnesses except accidental injuries.',
        page: 18,
        clause: '6.1.a',
        explanation: 'Hospital admissions within the first 30 days of the policy are not payable unless caused by an accidental injury.',
        plainMeaning: 'After 30 days from your policy start date, all fresh illnesses are covered.',
        iconName: 'Clock'
      },
      {
        field: 'ped_waiting_period',
        title: 'Pre-existing Disease (PED) Waiting',
        category: 'waiting',
        value: '36 Months (3 Years)',
        status: 'warning',
        quote: 'Benefits will not be available for any Pre-existing Condition until 36 months of continuous coverage have elapsed.',
        page: 19,
        clause: '6.1.c',
        explanation: 'Conditions declared prior to taking the policy (e.g., Diabetes, Hypertension) will be covered after 36 continuous months.',
        plainMeaning: 'Pre-existing health conditions become payable once you complete 3 continuous policy years.',
        iconName: 'ShieldAlert'
      },
      {
        field: 'specific_disease_waiting_period',
        title: 'Specific Disease Waiting Period',
        category: 'waiting',
        value: '24 Months (2 Years)',
        status: 'warning',
        quote: 'A waiting period of 24 months applies for specified treatments including Cataract, Hernia, Hysterectomy, and Joint Replacement.',
        page: 20,
        clause: '6.1.b',
        explanation: 'Common planned surgical procedures like Cataract, Gall stones, and Hernia have a standard 2-year waiting window.',
        plainMeaning: 'Planned surgeries are payable only after 2 consecutive years of policy renewal.',
        iconName: 'Calendar'
      },
      {
        field: 'sub_limits',
        title: 'Disease-wise Sub-limits',
        category: 'procedures',
        value: 'No Sub-limits (Except Modern Treatments as per IRDAI)',
        status: 'covered',
        quote: 'No disease-specific sub-limits apply for cardiac procedures, cancer, or kidney ailments up to the Sum Insured.',
        page: 23,
        clause: '4.8',
        explanation: 'There is no artificial cap on major critical illnesses; claim settlements are permitted up to the full ₹10 Lakh sum insured.',
        plainMeaning: 'You are protected against unexpected low caps during expensive hospital treatments.',
        iconName: 'CheckCircle2'
      },
      {
        field: 'pre_post_hospitalization',
        title: 'Pre & Post Hospitalization Days',
        category: 'logistics',
        value: '60 Days Pre / 180 Days Post',
        status: 'covered',
        quote: 'Medical expenses incurred 60 days before admission and 180 days after discharge are covered.',
        page: 14,
        clause: '4.5.1',
        explanation: 'Pharmacy bills, diagnostic tests, and doctor visits within 60 days prior and 180 days after discharge can be reimbursed.',
        plainMeaning: 'Keep all doctor prescription receipts and scan bills for 6 months after discharge for reimbursement.',
        iconName: 'Receipt'
      },
      {
        field: 'claim_intimation_deadline',
        title: 'Claim Intimation Deadline',
        category: 'logistics',
        value: '24 Hours (Emergency) / 48 Hours (Planned)',
        status: 'covered',
        quote: 'Intimation must be given to the Company within 24 hours of emergency hospitalization and 48 hours prior to planned admission.',
        page: 27,
        clause: '7.2',
        explanation: 'Notify your insurer/TPA desk immediately upon hospital entry to avoid procedural cashless delays.',
        plainMeaning: 'Inform the TPA within 24 hours of arriving at the hospital.',
        iconName: 'BellRing'
      },
      {
        field: 'sum_insured',
        title: 'Sum Insured Base & Multiplier',
        category: 'caps',
        value: '₹ 10,00,000 (with 2X Secure Benefit = ₹ 20,00,000)',
        status: 'covered',
        quote: 'The Base Sum Insured is enhanced by Secure Benefit providing 2X coverage from Day 1.',
        page: 9,
        clause: '3.1',
        explanation: 'Your base protection is ₹10 Lakhs, effectively doubled to ₹20 Lakhs coverage.',
        plainMeaning: 'Your effective coverage ceiling is ₹20 Lakhs.',
        iconName: 'Award'
      }
    ]
  },
  {
    id: 'star-health-comprehensive',
    insurerName: 'Star Health and Allied Insurance',
    policyName: 'Star Comprehensive Insurance Policy',
    policyNumber: 'STAR-COMP-2026-44102',
    sumInsured: '₹ 5,00,000',
    policyPeriod: '15 Mar 2026 – 14 Mar 2027',
    familyMembers: '2 (Self + Spouse)',
    userName: 'Ramesh',
    insurerHelpline: '1800 425 2255',
    tpaName: 'Star Health In-House Claims',
    tpaHelpline: '044 2828 8800',
    cashlessNumber: 'STAR-AUTH-90812',
    fields: [
      {
        field: 'room_rent_cap',
        title: 'Room Rent Limit',
        category: 'caps',
        value: '1% of Sum Insured (₹ 5,000 / day)',
        status: 'warning',
        quote: 'Room, boarding, and nursing expenses as provided by the Hospital up to 1% of the Sum Insured per day.',
        page: 8,
        clause: '1.A.a',
        explanation: 'Daily room rent is capped at ₹5,000/day. Choosing a costlier room triggers proportionate deductions on total hospital bills.',
        plainMeaning: 'If you choose a room costing ₹8,000/day, insurer will deduct ~37.5% across your doctor and operation charges.',
        iconName: 'Bed',
        relatedFields: [
          { title: 'ICU charges', clause: '1.A.b', page: 8 },
          { title: 'Nursing charges', clause: '1.A.a', page: 8 }
        ]
      },
      {
        field: 'icu_cap',
        title: 'ICU Charges Limit',
        category: 'caps',
        value: '2% of Sum Insured (₹ 10,000 / day)',
        status: 'warning',
        quote: 'ICU / ICCU expenses are covered up to a maximum of 2% of the Sum Insured per day.',
        page: 8,
        clause: '1.A.b',
        explanation: 'ICU charges are restricted to ₹10,000 per day. Excess ICU rates will not be reimbursed.',
        plainMeaning: 'Make sure ICU daily charges stay under ₹10,000 to avoid non-payable hospital expenses.',
        iconName: 'Activity'
      },
      {
        field: 'copay_percentage',
        title: 'Co-payment Requirement',
        category: 'caps',
        value: '10% for age 61 and above',
        status: 'warning',
        quote: 'A co-payment of 10% applies to each and every admissible claim for persons aged 61 years and above at entry.',
        page: 14,
        clause: '3.B',
        explanation: 'If a member is above 61 years, 10% of every approved bill must be paid out-of-pocket.',
        plainMeaning: 'You will pay 10% of the admissible bill if the patient entered the policy at age 61+.',
        iconName: 'Percent'
      },
      {
        field: 'initial_waiting_period',
        title: 'Initial Waiting Period',
        category: 'waiting',
        value: '30 Days',
        status: 'covered',
        quote: 'A waiting period of 30 days is applicable for any disease contracted by the insured except accidental injuries.',
        page: 11,
        clause: '2.1',
        explanation: 'Illnesses diagnosed within the first 30 days are excluded.',
        plainMeaning: '30-day initial buffer from policy start date.',
        iconName: 'Clock'
      },
      {
        field: 'ped_waiting_period',
        title: 'Pre-existing Disease (PED) Waiting',
        category: 'waiting',
        value: '36 Months (3 Years)',
        status: 'warning',
        quote: 'Pre-existing diseases will be covered after 36 consecutive months of continuous coverage.',
        page: 12,
        clause: '2.3',
        explanation: 'Declared pre-existing conditions are payable only after 3 full years.',
        plainMeaning: 'Declared past illnesses are covered from year 4 onwards.',
        iconName: 'ShieldAlert'
      },
      {
        field: 'specific_disease_waiting_period',
        title: 'Specific Disease Waiting Period',
        category: 'waiting',
        value: '24 Months (2 Years)',
        status: 'warning',
        quote: '24 months waiting period for specified ailments like stones in biliary system, hernia, and benign prostatic hypertrophy.',
        page: 12,
        clause: '2.2',
        explanation: 'Surgeries for hernia, stones, or hydrocele have a 24-month waiting duration.',
        plainMeaning: 'Planned treatments for common ailments are covered after 2 years.',
        iconName: 'Calendar'
      },
      {
        field: 'sub_limits',
        title: 'Disease-wise Sub-limits',
        category: 'procedures',
        value: 'Cataract capped at ₹ 30,000 per eye',
        status: 'warning',
        quote: 'Cataract surgery expenses are limited to ₹ 30,000 per eye and maximum ₹ 45,000 per policy period.',
        page: 15,
        clause: '4.C',
        explanation: 'Even if your total bill for cataract is ₹60,000, insurer will settle only up to ₹30,000.',
        plainMeaning: 'Lens and cataract bills have a hard limit of ₹30,000.',
        iconName: 'AlertCircle'
      },
      {
        field: 'pre_post_hospitalization',
        title: 'Pre & Post Hospitalization Days',
        category: 'logistics',
        value: '60 Days Pre / 90 Days Post',
        status: 'covered',
        quote: 'Pre-hospitalization expenses for 60 days and post-hospitalization expenses up to 90 days are covered.',
        page: 9,
        clause: '1.D',
        explanation: '60 days before hospital admission and 90 days post-discharge doctor/medicine receipts are payable.',
        plainMeaning: 'Save receipts for 60 days before and 90 days after discharge.',
        iconName: 'Receipt'
      },
      {
        field: 'claim_intimation_deadline',
        title: 'Claim Intimation Deadline',
        category: 'logistics',
        value: '24 Hours (Emergency) / 24 Hours (Planned)',
        status: 'covered',
        quote: 'In respect of planned hospitalization, intimation should be given 24 hours prior and for emergency within 24 hours.',
        page: 17,
        clause: '5.A',
        explanation: 'Inform insurer within 24 hours of hospital entry.',
        plainMeaning: 'Contact TPA desk within 24 hours.',
        iconName: 'BellRing'
      },
      {
        field: 'sum_insured',
        title: 'Sum Insured Ceiling',
        category: 'caps',
        value: '₹ 5,00,000 (Annual Floater)',
        status: 'covered',
        quote: 'The maximum indemnity under this policy shall not exceed the Sum Insured of ₹ 5,00,000.',
        page: 4,
        clause: 'Schedule A',
        explanation: 'The annual limit for all hospitalizations combined is ₹5 Lakhs.',
        plainMeaning: 'Your maximum total cover is ₹5 Lakhs.',
        iconName: 'Award'
      }
    ]
  },
  {
    id: 'care-supreme',
    insurerName: 'Care Health Insurance',
    policyName: 'Care Supreme',
    policyNumber: 'CARE-SUP-2026-78941',
    sumInsured: '₹ 15,00,000',
    policyPeriod: '10 Feb 2026 – 09 Feb 2027',
    familyMembers: '3 (Self + Spouse + 1 Child)',
    userName: 'Ananya',
    insurerHelpline: '1800 102 4455',
    tpaName: 'Care Health In-House TPA',
    tpaHelpline: '0124 449 4100',
    cashlessNumber: 'CARE-AUTH-55419',
    fields: [
      {
        field: 'room_rent_cap',
        title: 'Room Rent Limit',
        category: 'caps',
        value: 'No Cap (Any Category Room)',
        status: 'covered',
        quote: 'Room Rent and Boarding expenses with No Room Rent Capping across any room type.',
        page: 7,
        clause: '2.1.a',
        explanation: 'Choose any room without proportionate deduction risks.',
        plainMeaning: 'Full freedom of room category choice without billing penalties.',
        iconName: 'Bed'
      },
      {
        field: 'icu_cap',
        title: 'ICU Charges Limit',
        category: 'caps',
        value: 'No Sub-limit (Up to Sum Insured)',
        status: 'covered',
        quote: 'ICU / HDU charges are payable up to the Sum Insured.',
        page: 7,
        clause: '2.1.b',
        explanation: 'ICU treatments covered in full up to ₹15 Lakhs.',
        plainMeaning: 'Complete coverage for ICU stays.',
        iconName: 'Activity'
      },
      {
        field: 'copay_percentage',
        title: 'Co-payment Requirement',
        category: 'caps',
        value: '0% (Nil Co-payment)',
        status: 'covered',
        quote: 'No mandatory co-payment on admissible claim expenses.',
        page: 10,
        clause: '4.1',
        explanation: 'Zero co-pay required.',
        plainMeaning: 'No out-of-pocket percentage deduction.',
        iconName: 'Percent'
      },
      {
        field: 'initial_waiting_period',
        title: 'Initial Waiting Period',
        category: 'waiting',
        value: '30 Days',
        status: 'covered',
        quote: '30 days initial waiting period from the policy start date.',
        page: 12,
        clause: '5.1',
        explanation: 'Standard 30-day initial buffer for fresh illnesses.',
        plainMeaning: 'Covered after 30 days from purchase.',
        iconName: 'Clock'
      },
      {
        field: 'ped_waiting_period',
        title: 'Pre-existing Disease (PED) Waiting',
        category: 'waiting',
        value: '36 Months (Modifiable to 12/24m)',
        status: 'warning',
        quote: 'Pre-existing diseases covered after 36 months of continuous renewals.',
        page: 13,
        clause: '5.3',
        explanation: '36-month waiting period on declared chronic illnesses.',
        plainMeaning: 'Pre-existing conditions covered after 3 years.',
        iconName: 'ShieldAlert'
      },
      {
        field: 'specific_disease_waiting_period',
        title: 'Specific Disease Waiting Period',
        category: 'waiting',
        value: '24 Months (2 Years)',
        status: 'warning',
        quote: '24 months waiting period for specified listed ailments.',
        page: 13,
        clause: '5.2',
        explanation: '2 years waiting for standard surgeries.',
        plainMeaning: 'Planned surgeries covered after 2 years.',
        iconName: 'Calendar'
      },
      {
        field: 'sub_limits',
        title: 'Disease-wise Sub-limits',
        category: 'procedures',
        value: 'No Sub-limits on Major Surgeries',
        status: 'covered',
        quote: 'No sub-limits on heart treatments, cancer care, or joint replacement.',
        page: 16,
        clause: '2.8',
        explanation: 'Major surgeries settled up to the full ₹15 Lakhs limit.',
        plainMeaning: 'No caps on surgical procedures.',
        iconName: 'CheckCircle2'
      },
      {
        field: 'pre_post_hospitalization',
        title: 'Pre & Post Hospitalization Days',
        category: 'logistics',
        value: '60 Days Pre / 180 Days Post',
        status: 'covered',
        quote: 'Covered up to 60 days before admission and 180 days post discharge.',
        page: 8,
        clause: '2.2',
        explanation: '60 days pre and 180 days post hospital OPD/medicine reimbursement.',
        plainMeaning: 'Reimburse medicines & tests for 6 months after discharge.',
        iconName: 'Receipt'
      },
      {
        field: 'claim_intimation_deadline',
        title: 'Claim Intimation Deadline',
        category: 'logistics',
        value: '24 Hours Emergency / 48 Hours Planned',
        status: 'covered',
        quote: 'Notify company within 24 hours of emergency hospitalization.',
        page: 20,
        clause: '7.1',
        explanation: 'Intimate TPA within 24 hours of hospital admission.',
        plainMeaning: 'Inform TPA within 24 hours.',
        iconName: 'BellRing'
      },
      {
        field: 'sum_insured',
        title: 'Sum Insured Ceiling',
        category: 'caps',
        value: '₹ 15,00,000 + 500% Cumulative Bonus',
        status: 'covered',
        quote: 'Sum Insured of ₹ 15,00,000 with Cumulative Bonus Super up to 500%.',
        page: 5,
        clause: '3.2',
        explanation: '₹15 Lakhs base coverage with progressive no-claim bonus expansion.',
        plainMeaning: '₹15 Lakhs primary coverage.',
        iconName: 'Award'
      }
    ]
  },
  {
    id: 'niva-bupa-reassure',
    insurerName: 'Niva Bupa Health Insurance',
    policyName: 'ReAssure 2.0',
    policyNumber: 'NIVA-REA-2026-61209',
    sumInsured: '₹ 10,00,000',
    policyPeriod: '01 Jun 2026 – 31 May 2027',
    familyMembers: '2 (Self + 1 Child)',
    userName: 'Kavitha',
    insurerHelpline: '1860 500 8888',
    tpaName: 'Niva Bupa In-House TPA',
    tpaHelpline: '011 4123 4567',
    cashlessNumber: 'NIVA-AUTH-44120',
    fields: [
      {
        field: 'room_rent_cap',
        title: 'Room Rent Limit',
        category: 'caps',
        value: 'No Cap (Any Room Category)',
        status: 'covered',
        quote: 'Any Room Category without any sub-limit or proportionate deduction.',
        page: 9,
        clause: 'Section 2.1',
        explanation: 'Choose any room without restriction.',
        plainMeaning: 'No daily room rent cap.',
        iconName: 'Bed'
      },
      {
        field: 'icu_cap',
        title: 'ICU Charges Limit',
        category: 'caps',
        value: 'Up to Sum Insured',
        status: 'covered',
        quote: 'Intensive Care Unit charges are covered up to the Sum Insured.',
        page: 9,
        clause: 'Section 2.2',
        explanation: 'ICU covered up to ₹10 Lakhs.',
        plainMeaning: 'Full ICU coverage.',
        iconName: 'Activity'
      },
      {
        field: 'copay_percentage',
        title: 'Co-payment Requirement',
        category: 'caps',
        value: '0% (Nil Co-payment)',
        status: 'covered',
        quote: 'Nil Co-payment across all network hospitals.',
        page: 11,
        clause: 'Section 3.1',
        explanation: 'Zero mandatory co-pay.',
        plainMeaning: 'No co-payment required.',
        iconName: 'Percent'
      },
      {
        field: 'initial_waiting_period',
        title: 'Initial Waiting Period',
        category: 'waiting',
        value: '30 Days',
        status: 'covered',
        quote: '30 days waiting period applies for illnesses from policy inception.',
        page: 14,
        clause: 'Section 4.1',
        explanation: '30 days standard initial window.',
        plainMeaning: 'Active after 30 days.',
        iconName: 'Clock'
      },
      {
        field: 'ped_waiting_period',
        title: 'Pre-existing Disease (PED) Waiting',
        category: 'waiting',
        value: '36 Months (3 Years)',
        status: 'warning',
        quote: '36 months waiting period for pre-existing medical conditions.',
        page: 15,
        clause: 'Section 4.2',
        explanation: 'Pre-existing diseases covered after 3 years.',
        plainMeaning: 'Past conditions covered after 36 months.',
        iconName: 'ShieldAlert'
      },
      {
        field: 'specific_disease_waiting_period',
        title: 'Specific Disease Waiting Period',
        category: 'waiting',
        value: '24 Months (2 Years)',
        status: 'warning',
        quote: '24 months waiting period for specified common ailments.',
        page: 15,
        clause: 'Section 4.3',
        explanation: '2-year waiting on planned surgeries.',
        plainMeaning: 'Planned surgeries covered in Year 3.',
        iconName: 'Calendar'
      },
      {
        field: 'sub_limits',
        title: 'Disease-wise Sub-limits',
        category: 'procedures',
        value: 'No Sub-limits (Unlimited ReAssure Forever)',
        status: 'covered',
        quote: 'No disease specific financial capping.',
        page: 18,
        clause: 'Section 2.9',
        explanation: 'Unlimited reinstatements of sum insured for subsequent hospitalizations.',
        plainMeaning: 'No sub-limits on covered treatments.',
        iconName: 'CheckCircle2'
      },
      {
        field: 'pre_post_hospitalization',
        title: 'Pre & Post Hospitalization Days',
        category: 'logistics',
        value: '60 Days Pre / 180 Days Post',
        status: 'covered',
        quote: 'Medical expenses for 60 days prior and 180 days after hospitalisation.',
        page: 10,
        clause: 'Section 2.3',
        explanation: '60/180 days pre/post hospitalization expenses covered.',
        plainMeaning: '6 months post-discharge medicine bills covered.',
        iconName: 'Receipt'
      },
      {
        field: 'claim_intimation_deadline',
        title: 'Claim Intimation Deadline',
        category: 'logistics',
        value: '24 Hours Emergency / 48 Hours Planned',
        status: 'covered',
        quote: 'Intimate within 24 hours of emergency admission.',
        page: 22,
        clause: 'Section 6.1',
        explanation: 'Inform TPA within 24 hours.',
        plainMeaning: 'Intimate within 24 hours.',
        iconName: 'BellRing'
      },
      {
        field: 'sum_insured',
        title: 'Sum Insured Ceiling',
        category: 'caps',
        value: '₹ 10,00,000 + Lock The Clock Benefit',
        status: 'covered',
        quote: 'Sum Insured of ₹ 10,00,000 with Age Lock until first claim.',
        page: 6,
        clause: 'Section 1.1',
        explanation: '₹10 Lakhs base sum insured.',
        plainMeaning: '₹10 Lakhs coverage.',
        iconName: 'Award'
      }
    ]
  },
  {
    id: 'arogya-sanjeevani',
    insurerName: 'Standard IRDAI Policy',
    policyName: 'Arogya Sanjeevani Standard Policy',
    policyNumber: 'IRDAI-AS-2026-10293',
    sumInsured: '₹ 5,00,000',
    policyPeriod: '01 Apr 2026 – 31 Mar 2027',
    familyMembers: '1 (Individual)',
    userName: 'Vikram',
    insurerHelpline: '1800 220 233',
    tpaName: 'Medi Assist TPA',
    tpaHelpline: '080 2206 7000',
    cashlessNumber: 'MEDI-IRDAI-9102',
    fields: [
      {
        field: 'room_rent_cap',
        title: 'Room Rent Limit',
        category: 'caps',
        value: '2% of SI or max ₹ 5,000 / day',
        status: 'warning',
        quote: 'Room Rent, Boarding and Nursing expenses up to 2% of Sum Insured subject to a maximum of ₹ 5,000 per day.',
        page: 5,
        clause: 'Clause 4.1',
        explanation: 'Standard IRDAI room cap: 2% of SI or maximum ₹5,000/day. Proportionate deduction applies for higher rooms.',
        plainMeaning: 'Exceeding ₹5,000/day room will lead to proportional deduction across your surgery and doctor bills.',
        iconName: 'Bed',
        relatedFields: [
          { title: 'ICU charges', clause: 'Clause 4.2', page: 5 }
        ]
      },
      {
        field: 'icu_cap',
        title: 'ICU Charges Limit',
        category: 'caps',
        value: '5% of SI or max ₹ 10,000 / day',
        status: 'warning',
        quote: 'Intensive Care Unit charges up to 5% of Sum Insured subject to maximum of ₹ 10,000 per day.',
        page: 5,
        clause: 'Clause 4.2',
        explanation: 'ICU charges capped at ₹10,000 per day.',
        plainMeaning: 'ICU stays above ₹10,000/day are not fully payable.',
        iconName: 'Activity'
      },
      {
        field: 'copay_percentage',
        title: 'Co-payment Requirement',
        category: 'caps',
        value: '5% Mandatory Co-payment',
        status: 'warning',
        quote: 'A co-payment of 5% is applicable on each and every claim amount.',
        page: 8,
        clause: 'Clause 6.1',
        explanation: '5% of every admissible hospital claim must be paid by the policyholder.',
        plainMeaning: 'You will always pay 5% of the total approved hospital bill.',
        iconName: 'Percent'
      },
      {
        field: 'initial_waiting_period',
        title: 'Initial Waiting Period',
        category: 'waiting',
        value: '30 Days',
        status: 'covered',
        quote: '30-day initial waiting period for all illnesses.',
        page: 9,
        clause: 'Clause 5.1',
        explanation: 'First 30 days excluded for fresh medical sickness.',
        plainMeaning: 'Covered after 30 days.',
        iconName: 'Clock'
      },
      {
        field: 'ped_waiting_period',
        title: 'Pre-existing Disease (PED) Waiting',
        category: 'waiting',
        value: '48 Months (4 Years)',
        status: 'warning',
        quote: 'Pre-existing diseases are covered after 48 months of continuous coverage.',
        page: 10,
        clause: 'Clause 5.3',
        explanation: 'Standard statutory 4-year waiting on declared chronic illnesses.',
        plainMeaning: 'Past conditions covered after 4 continuous policy years.',
        iconName: 'ShieldAlert'
      },
      {
        field: 'specific_disease_waiting_period',
        title: 'Specific Disease Waiting Period',
        category: 'waiting',
        value: '24 & 48 Months Tiered',
        status: 'warning',
        quote: '24 months for common ailments and 48 months for joint replacements.',
        page: 10,
        clause: 'Clause 5.2',
        explanation: '2 years for hernia/stones, 4 years for joint replacement.',
        plainMeaning: 'Standard 2 to 4 years waiting for listed surgeries.',
        iconName: 'Calendar'
      },
      {
        field: 'sub_limits',
        title: 'Disease-wise Sub-limits',
        category: 'procedures',
        value: 'Cataract (25% or ₹40k), Modern treatments (50%)',
        status: 'warning',
        quote: 'Cataract surgery up to 25% of SI or ₹ 40,000 per eye; modern robotic treatments up to 50% of SI.',
        page: 7,
        clause: 'Clause 4.6',
        explanation: 'Statutory caps apply on cataract, robotic surgeries, and stem cell therapies.',
        plainMeaning: 'Specific caps on eye surgeries and robotic treatments.',
        iconName: 'AlertCircle'
      },
      {
        field: 'pre_post_hospitalization',
        title: 'Pre & Post Hospitalization Days',
        category: 'logistics',
        value: '30 Days Pre / 60 Days Post',
        status: 'covered',
        quote: 'Medical expenses 30 days before hospitalization and 60 days post discharge.',
        page: 6,
        clause: 'Clause 4.3',
        explanation: '30 days pre-admission and 60 days post-discharge bills payable.',
        plainMeaning: 'Reimburse medicines for 30 days before and 60 days after hospital stay.',
        iconName: 'Receipt'
      },
      {
        field: 'claim_intimation_deadline',
        title: 'Claim Intimation Deadline',
        category: 'logistics',
        value: '24 Hours Emergency / 48 Hours Planned',
        status: 'covered',
        quote: 'Intimate company within 24 hours of emergency admission.',
        page: 12,
        clause: 'Clause 7.1',
        explanation: 'Inform insurer within 24 hours.',
        plainMeaning: 'Intimate TPA within 24 hours.',
        iconName: 'BellRing'
      },
      {
        field: 'sum_insured',
        title: 'Sum Insured Ceiling',
        category: 'caps',
        value: '₹ 5,00,000 Standard Cap',
        status: 'covered',
        quote: 'Sum Insured limit of ₹ 5,00,000 as per standard IRDAI product design.',
        page: 3,
        clause: 'Clause 2.1',
        explanation: '₹5 Lakhs standardized annual coverage.',
        plainMeaning: '₹5 Lakhs total cover.',
        iconName: 'Award'
      }
    ]
  }
];
